### ISSUE TITLE
main.go:9:2: cannot find package "rest-and-go/store" in any of:

### ISSUE THREAD

**Issue by rjain15** [brainbreaker/rest-and-go#1]
This might be related to a GOPATH issue

But I cloned the repo and followed all the instructions. 

       `main.go:9:2: cannot find package "rest-and-go/store" in any of:
         /Users/rjain/go/src/xclo-demo-apps/rest-and-go/vendor/rest-and-go/store (vendor tree)
        /usr/local/Cellar/go/1.9.3/libexec/src/rest-and-go/store (from $GOROOT)
        /Users/rjain/go/src/rest-and-go/store (from $GOPATH)
        /Users/rjain/code/xclo/xclo-demo-apps/go/src/rest-and-go/store`

**Comment by kgwebsites** [comment]
@rjain15 Yeah I had the same GOPATH issue. Problem is the GOPATH is overriding the local path which is why go can't find the package. In main.go change the "rest-and-go/store" to just "./store"
